import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import {useEffect} from "react";


export default function Home() {

  useEffect(() => {
    const closeifobox = document.getElementById("closeinfobox") as HTMLInputElement | null;
    const contactinfo = document.getElementById('contactid') as HTMLInputElement | null;
    const ifobox = document.getElementById('infobox') as HTMLInputElement | null;
    ifobox!.style.visibility = 'hidden';
    contactinfo?.addEventListener('click', function handleClick(event) {
    ifobox!.style.visibility = 'visible'; 
    });
    closeifobox?.addEventListener('click', function handleClick(event) {
    ifobox!.style.visibility = 'hidden'; 
    });
  }, []);

  
  return (
    <div className={styles.container}>
      <Head>
        <title>EndWithBoredom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id='infobox' className={styles.info}>
        <div id='closeinfobox'>Close</div>
        E-mail: balcerzakmateuszkontakt@gmail.com</div>
      <header className={styles.headercontainer}>
        <img className={styles.img} src="" alt="" />
        <h1>EndWithBoredom</h1>
      </header>
      <h2 className={styles.oneplayer}>1-Player Games:</h2>
      <section className={styles.onesectioncontainer}>
        <div className={styles["box"] + " " + styles["wordle"]}></div>
        <div className={styles["box"] + " " + styles["sudoku"]}></div>
        <div className={styles["box"] + " " + styles["flappybird"]}></div>
        <div className={styles["box"] + " " + styles["wordle2"]}></div>
      </section>
        <h2 className={styles.twoplayer}>2-Player Games:</h2>
        <section className={styles.twosectioncontainer}>
        <div className={styles["box"] + " " + styles["wordle"]}></div>
        <div className={styles["box"] + " " + styles["sudoku"]}></div>
        <div className={styles["box"] + " " + styles["flappybird"]}></div>
        <div className={styles["box"] + " " + styles["wordle2"]}></div>
      </section>
      <footer className={styles.footerContainer}>
        <div className={styles.footertext}>
          <Link id='contactid' className={styles["link"] + " " + styles["contact"]}  href="">Contact</Link>
          <Link className={styles["link"] + " " + styles["donate"]}  href="https://www.patreon.com/user?u=83366049">Donate</Link>
        </div>
      </footer>
      <script src='../scripts/index.ts'></script>
    </div>
)
}
